export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST';
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_FAIL = 'PLACE_ORDER_FAIL';
export const MY_ORDERS_REQUEST = 'MY_ORDERS_REQUEST';
export const MY_ORDERS_SUCCESS = 'MY_ORDERS_SUCCESS';
export const MY_ORDERS_FAIL = 'MY_ORDERS_FAIL';
export const MY_ORDERS_RESET = 'MY_ORDERS_RESET';
export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';
export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';
export const SAVE_BILLING_ADDRESS = 'SAVE_BILLING_ADDRESS';
export const SAVE_SHIPPING_ADDRESS = 'SAVE_SHIPPING_ADDRESS';

// Admin
export const ADMIN_GET_ORDERS_REQUEST = 'ADMIN_GET_ORDERS_REQUEST';
export const ADMIN_GET_ORDERS_SUCCESS = 'ADMIN_GET_ORDERS_SUCCESS';
export const ADMIN_GET_ORDERS_FAIL = 'ADMIN_GET_ORDERS_FAIL';
export const ADMIN_ORDER_REVIEW_REQUEST = 'ADMIN_ORDER_REVIEW_REQUEST';
export const ADMIN_ORDER_REVIEW_SUCCESS = 'ADMIN_ORDER_REVIEW_SUCCESS';
export const ADMIN_ORDER_REVIEW_FAIL = 'ADMIN_GET_ORDERS_FAIL';
export const ORDER_DISPATCH_REQUEST = 'ORDER_DISPATCH_REQUEST';
export const ORDER_DISPATCH_SUCCESS = 'ORDER_DISPATCH_SUCCESS';
export const ORDER_DISPATCH_FAIL = 'ORDER_DISPATCH_FAIL';
export const ORDER_DISPATCH_RESET = 'ORDER_DISPATCH_RESET';
